name: Check

on:
    push:
        branches: [master]
    pull_request:

    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
              with:
                  submodules: true
            - name: Prepare Node Environment
              uses: actions/setup-node@v7
              with:
                  node-version: 24
                  cache: 'npm'
            - name: Install Native Dependencies
              run: |
                  sudo apt update
                  sudo apt install -y libwebkit2gtk-4.1-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
            - name: Install Dependencies
              run: npm ci
            - name: Lint
              run: make check
